-- begin TRACKER_PROJECT
alter table TRACKER_PROJECT add constraint FK_TRACKER_PROJECT_CATEGORY_ID foreign key (CATEGORY_ID) references SYS_CATEGORY(ID)^
create unique index IDX_TRACKER_PROJECT_UNIQ_SHORT_NAME on TRACKER_PROJECT (SHORT_NAME) ^
create index IDX_TRACKER_PROJECT_CATEGORY on TRACKER_PROJECT (CATEGORY_ID)^
-- end TRACKER_PROJECT
-- begin TRACKER_ISSUE
alter table TRACKER_ISSUE add constraint FK_TRACKER_ISSUE_PROJECT_ID foreign key (PROJECT_ID) references TRACKER_PROJECT(ID)^
alter table TRACKER_ISSUE add constraint FK_TRACKER_ISSUE_ASSIGNEE_ID foreign key (ASSIGNEE_ID) references SEC_USER(ID)^
alter table TRACKER_ISSUE add constraint FK_TRACKER_ISSUE_CREATED_ID foreign key (CREATED_ID) references SEC_USER(ID)^
create index IDX_TRACKER_ISSUE_ASSIGNEE on TRACKER_ISSUE (ASSIGNEE_ID)^
create index IDX_TRACKER_ISSUE_CREATED on TRACKER_ISSUE (CREATED_ID)^
create index IDX_TRACKER_ISSUE_PROJECT on TRACKER_ISSUE (PROJECT_ID)^
-- end TRACKER_ISSUE
-- begin TRACKER_PROJECT_USER_LINK
alter table TRACKER_PROJECT_USER_LINK add constraint FK_TPUL_PROJECT foreign key (PROJECT_ID) references TRACKER_PROJECT(ID)^
alter table TRACKER_PROJECT_USER_LINK add constraint FK_TPUL_USER foreign key (USER_ID) references SEC_USER(ID)^
-- end TRACKER_PROJECT_USER_LINK
